version: "3.7"
services:
  comments:
    image: ghcr.io/stwissel/blog-comments-public
    ports:
      - 8080:8080
    restart: always
    secrets:
      - source: activityPub
        target: "/opt/activityPub/users.json"
    environment:
      ClientSecret: ${ClientSecret}
      PORT: 8080
      ClientToken: ${ClientToken}
      PushToke: ${PushToken}
      PushUser: ${PushUser}
      OauthURL: bitbucket.org
      RepositoryURL: stwissel/blogsource
      CaptchaSecret: ${CaptchaSecret}
secrets:
  activityPub:
    file: ${ACTIVITY_USERS}