name: Release Comment Container

on:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -Djib.to.auth.username=Stwissel  -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
